name: Firestore data export
on:
  release:
    types: [prereleased]
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Jira Github Release Automation With Go
        uses: Geun-Oh/jira-github-release-automation-with-go@0.1.3
            
